<?xml version="1.0"?>
<robot name="mars_rover" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Material definitions -->
  <material name="silver">
    <color rgba="0.75 0.75 0.75 1.0"/>
  </material>
  
  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>

  <!-- Constants -->
  <xacro:property name="M_PI" value="3.1415926535897931"/>
  
  <!-- Rover dimensions -->
  <xacro:property name="chassis_length" value="0.8"/>
  <xacro:property name="chassis_width" value="0.6"/>
  <xacro:property name="chassis_height" value="0.3"/>
  <xacro:property name="chassis_mass" value="30.0"/>
  
  <!-- Wheel properties -->
  <xacro:property name="wheel_radius" value="0.15"/>
  <xacro:property name="wheel_width" value="0.08"/>
  <xacro:property name="wheel_mass" value="2.0"/>
  <xacro:property name="wheel_separation" value="0.68"/>

  <!-- ==================== BASE LINK (CHASSIS) ==================== -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="silver"/>
    </visual>
    
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <mass value="${chassis_mass}"/>
      <inertia
        ixx="1.5" ixy="0.0" ixz="0.0"
        iyy="2.0" iyz="0.0"
        izz="2.5"/>
    </inertial>
  </link>

  <!-- ==================== WHEEL MACRO ==================== -->
  <xacro:macro name="wheel" params="prefix y_offset">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="0.01" ixy="0.0" ixz="0.0"
          iyy="0.01" iyz="0.0"
          izz="0.01"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="0 ${y_offset} 0" rpy="${M_PI/2} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <!-- ==================== CASTER MACRO ==================== -->
  <xacro:macro name="caster" params="prefix x_offset">
    <link name="${prefix}_caster">
      <visual>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
        <material name="black"/>
      </visual>
      
      <collision>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
      </collision>
      
      <inertial>
        <mass value="0.5"/>
        <inertia
          ixx="0.001" ixy="0.0" ixz="0.0"
          iyy="0.001" iyz="0.0"
          izz="0.001"/>
      </inertial>
    </link>

    <joint name="${prefix}_caster_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_caster"/>
      <origin xyz="${x_offset} 0 -0.1" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- ==================== INSTANTIATE COMPONENTS ==================== -->
  
  <!-- Main wheels -->
  <xacro:wheel prefix="left" y_offset="0.34"/>
  <xacro:wheel prefix="right" y_offset="-0.34"/>
  
  <!-- Casters for stability -->
  <xacro:caster prefix="front" x_offset="0.3"/>
  <xacro:caster prefix="rear" x_offset="-0.3"/>

  <!-- ==================== GAZEBO PLUGINS ==================== -->
  
  <!-- Differential Drive Controller -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <update_rate>50</update_rate>
      
      <!-- Wheel Configuration -->
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
      
      <!-- Limits -->
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      
      <!-- Topics -->
      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      
      <!-- Odometry -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      
      <!-- Frames -->
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>
  </gazebo>

  <!-- ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robot_namespace>/</robot_namespace>
    </plugin>
  </gazebo>

</robot>